src/EStore.WebApp.MVC/Models/ErrorViewModel.cs
namespace EStore.WebApp.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/EStore.WebApp.MVC/Controllers/Admin/AdminProductController.cs
using EStore.Catalog.Application.Dtos;
using EStore.Catalog.Application.Services;
using Microsoft.AspNetCore.Mvc;

namespace EStore.WebApp.MVC.Controllers.Admin
{
    public class AdminProductController : Controller
    {
        private readonly IProductAppService _productAppService;

        public AdminProductController(IProductAppService productAppService)
        {
            _productAppService = productAppService;
        }

        [HttpGet]
        [Route("admin-product")]
        public async Task<IActionResult> Index()
        {
            return View(await _productAppService.GetAll());
        }

        [HttpGet]
        [Route("new-product")]
        public async Task<IActionResult> NewProduct()
        {
            return View(await FillCategories(new ProductDto()));
        }

        [HttpPost]
        [Route("new-product")]
        public async Task<IActionResult> NewProduct(ProductDto productDto)
        {

            ModelState.Remove("Image");
            ModelState.Remove("ImageUpload");
            if (!ModelState.IsValid) return View(await FillCategories(productDto));
            var imgId = Guid.NewGuid() + "_";
            if (!await UploadFile(productDto.ImageUpload, imgId))
            {
                return View(productDto);
            }

            productDto.Image = imgId + productDto.ImageUpload.FileName;

            await _productAppService.AddProduct(productDto);

            return RedirectToAction("Index");

        }

        [HttpGet]
        [Route("update-product")]
        public async Task<IActionResult> UpdateProduct(Guid id)
        {
            return View(await FillCategories(await _productAppService.GetById(id)));

        }

        [HttpPost]
        [Route("update-product")]
        public async Task<IActionResult> UpdateProduct(Guid id, ProductDto productDto)
        {

            if (id != productDto.Id) return NotFound(); 

            var product = await _productAppService.GetById(id);

            productDto.Image = product.Image;
            productDto.QtyStock = product.QtyStock;

            ModelState.Remove("Image");
            ModelState.Remove("ImageUpload");
            ModelState.Remove("QtyStock");


            if (!ModelState.IsValid) return View(await FillCategories(productDto));


            if (productDto.ImageUpload != null)
            {
                var imgId = Guid.NewGuid() + "_";
                if (!await UploadFile(productDto.ImageUpload, imgId))
                {
                    return View(productDto);
                }

                product.Image = imgId + productDto.ImageUpload.FileName;
            }

  
            await _productAppService.UpdateProduct(productDto);
            
            return RedirectToAction("Index");
        }


        [HttpPost]
        [Route("update-stock-product")]
        public async Task<IActionResult> UpdateStock(Guid id, int qty)
        {
            if (qty > 0)
            {
                await _productAppService.ReplenishmentStock(id, qty);
            }
            else 
            {
                await _productAppService.DebitStock(id, qty);
            }

            return View("index",await _productAppService.GetAll());
        }


        [HttpGet]
        [Route("update-stock-product")]
        public async Task<IActionResult> UpdateStock(Guid id)
        {
            
            return View("Stock", await _productAppService.GetById(id));
        }



        private async Task<ProductDto> FillCategories(ProductDto productDto)
        {
            productDto.Categories = await _productAppService.GetAllCategories();
            return productDto;
        }



        private async Task<bool> UploadFile(IFormFile imagemUpload, string imgId)
        {
            if (imagemUpload.Length <= 0)
            {
                ModelState.AddModelError(string.Empty, "Campo Imagem é obrigatório ");
                return false;
            }
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", imgId + imagemUpload.FileName);

            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await imagemUpload.CopyToAsync(stream);
            }

            return true;
        }
    }
}

src/EStore.WebApp.MVC/Controllers/HomeController.cs
using EStore.WebApp.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EStore.WebApp.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/EStore.WebApp.MVC/Controllers/Store/StoreController.cs
using EStore.Catalog.Application.Services;
using Microsoft.AspNetCore.Mvc;

namespace EStore.WebApp.MVC.Controllers.Store
{
    public class StoreController : Controller
    {

        private readonly IProductAppService _productAppService;

        public StoreController(IProductAppService productAppService)
        {
            _productAppService = productAppService;
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Index()
        {
            return View(await _productAppService.GetAll());
        }

        [HttpGet]
        [Route("store-products/{id}")]
        public async Task<IActionResult> ProductDetails(Guid id)
        {
            return View(await _productAppService.GetById(id));
        }


    }
}

src/EStore.WebApp.MVC/Views/AdminProduct/Index.cshtml
@model IEnumerable<EStore.Catalog.Application.Dtos.ProductDto>


@{
    ViewData["Title"] = "Produtos";
}



<div class="row">
    <h2>Administração de Produtos</h2>
</div>


<div >
    <a asp-controller="AdminProduct" asp-action="NewProduct" class="btn btn-success"> Adicionar Novo Produto</a>
</div>

<hr/>

<div class="row">

    @{
        foreach (var product  in Model.OrderBy(p => p.CategoryId))
        {
            <div class="col-md-2 col-sm-6" style="margin: 10px;">
                <span class="thumbnail">
                    <img width="200" height="200" src="~/Images/@product.Image" />
                    <h4>@product.Name</h4>
                    <p>@product.QtyStock em estoque</p>
                    <p>@product.Description</p>
                    <p class="price">@product.Price.ToString("C")</p>
                    <hr class="line">
                    <div class="row">
                        <a asp-controller="AdminProduct" asp-action="UpdateProduct" asp-route-id="@product.Id" class="btn btn-secondary" style="margin-bottom: 5px">Atualizar Produto</a>
                        
                        <a asp-controller="AdminProduct" asp-action="UpdateStock" asp-route-id="@product.Id" asp-route-qty="" class="btn btn-dark">Atualizar Estoque</a>
                    </div>
                </span>

            </div>
        }

    
    }

</div>

        

src/EStore.WebApp.MVC/Views/AdminProduct/NewProduct.cshtml
@model EStore.Catalog.Application.Dtos.ProductDto

@{
    ViewData["Title"] = "Novo Produto";
}

<h1>@ViewData["Title"]</h1>
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-controller="AdminProduct" asp-action="NewProduct">
            
            <vc:summary></vc:summary>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(Model.Categories, "Id", "Name"))">
                    <option></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>

                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="ImageUpload" asp-for="ImageUpload">
                    <label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="ImageUpload"></label>
                    <label style="display: none" id="img_nome"></label>
                </div>

                <span asp-validation-for="ImageUpload" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundity" class="control-label"></label>
                <input asp-for="Profundity" class="form-control" />
                <span asp-validation-for="Profundity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="QtyStock" class="control-label"></label>
                <input asp-for="QtyStock" class="form-control" />
                <span asp-validation-for="QtyStock" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-success" />
                <a  class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $("#ImageUpload").change(function){
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImageUpload").attr("data-val", "true");
        $("#ImageUpload").attr("data-val-required", "Preencha o campo Imagem");

    </script>
}

src/EStore.WebApp.MVC/Views/AdminProduct/Stock.cshtml
@model EStore.Catalog.Application.Dtos.ProductDto


@{
    ViewData["Title"] = "Editar Produto" ;
}

<div class="container">
    <div class="row">
        <div class="col-md-4 item-photo">
            <img width="400" height="400" src="~/Images/@Model.Image"/>
        </div>

        <div class="col-md-6" style="border:20px solid white">
            <h3>@Model.Name</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top:0px;">@Model.Price.ToString("C")</h3>

            <p>Apenas @Model.QtyStock em estoque!</p>
            <p>@Model.Description</p>

            <div class="section" style="padding-bottom:20px;">

                <form method="post" asp-asp-controller="AdminProduct" asp-action="UpdateStock">
                   <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
                   <input type="text" id="qty" name="qty" />
                   <button class="btn btn-success">Atualizar Estoque</button>
                   <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
                </form>
            </div>
        </div>
    </div>
</div>

src/EStore.WebApp.MVC/Views/AdminProduct/UpdateProduct.cshtml
@model EStore.Catalog.Application.Dtos.ProductDto


@{
    ViewData["Title"] = "Editar " + Model.Name;
}

<h4>@ViewData["Title"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="UpdateProduct">
            <vc:summary></vc:summary>


            <input type="hidden" asp-for="Id" />


            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="@(new SelectList(Model.Categories, "Id", "Name"))">
                    <option></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>

                <div class="custom-file">
                    <input type="text" class="custom-file-input" id="Image" asp-for="Image">
                    <label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="Image"></label>
                    <label style="display: none" id="img_nome"></label>
                </div>

                <span asp-validation-for="Image" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Profundity" class="control-label"></label>
                <input asp-for="Profundity" class="form-control" />
                <span asp-validation-for="Profundity" class="text-danger"></span>
            </div>


            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" />
                <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
            </div>
        </form>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

  
}

src/EStore.WebApp.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/EStore.WebApp.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EStore.WebApp.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EStore.WebApp.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EStore.WebApp.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminProduct" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EStore.WebApp.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/EStore.WebApp.MVC/Views/Store/Index.cshtml
@model IEnumerable<EStore.Catalog.Application.Dtos.ProductDto>


@{
    ViewData["Title"] = "Produtos";
}



<div class="row">
    <h2>Produtos</h2>
</div>


<hr/>

<div class="row">

    @{
        foreach (var product  in Model.OrderBy(p => p.CategoryId))
        {
            <div class="col-md-2 col-sm-6" style="margin: 10px;">
                <span class="thumbnail">
                    <a asp-controller="Store" asp-action="ProductDetails" asp-route-id="@product.Id"><img width="200" height="200" src="~/Images/@product.Image" /></a>
                    <h4>@product.Name</h4>
                    <p>@product.QtyStock em estoque</p>
                    <p>@product.Description</p>
                    <p class="price">@product.Price.ToString("C")</p>
                </span>

            </div>
        }

    
    }

</div>

src/EStore.WebApp.MVC/Views/Store/ProductDetails.cshtml
@model EStore.Catalog.Application.Dtos.ProductDto


@{
    ViewData["Title"] = "Detalhe Produto" + Model.Name;
}

<h4>@ViewData["Title"]</h4>
<hr />

<div class="container">
    <div class="row">
        <div class="col-md-4 item-photo">
            <img width="400" height="400" src="~/Images/@Model.Image"/>
        </div>

        <div class="col-md-6" style="border:20px solid white">
            <h3>@Model.Name</h3>

            <h6 class="title-price"><small>OFERTA</small></h6>
            <h3 style="margin-top:0px;">@Model.Price.ToString("C")</h3>

            <p>Apenas @Model.QtyStock em estoque!</p>
            <p>@Model.Description</p>

            <div class="section" style="padding-bottom: 20px;">
                <h6 class="title-attr"><small>QUANTIDADE</small></h6>
                
                <div>
                    <div class="btn-minus"><span style="font-size: 15px">-</span></div>
                    <input style="font-size: 15px" type="text" value="1"/>
                    <div class="btn-plus"><span style="font-size: 15px">+</span></div>
                </div>
            </div>
            
            <div class="section" style="padding-bottom: 20px">
                <button class="btn btn-success"><span style="margin: 0 20px 0 20px" aria-hidden="true">COMPRAR</span></button>
            </div>
        </div>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }


}